spring:
  application:
    name: user-service
  transaction:
    rollback-on-commit-failure: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Jason
    url: jdbc:mysql://39.97.103.190/learning-platform?useSSL=false&serverTimezone=GMT%2B8
eureka:
  client:
    service-url:
      defaultZone: http://server1:1111/eureka
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.jason.usermodule.model
server:
  port: 91
